[package]
name = "raylock"
version = "0.1.0"
edition = "2021"

[dependencies]
battery = "0.7.8"
chrono = "0.4.38"
eframe = "0.28"
egui = "0.28"
os_info = "3.8.2"
rand = "0.8.5"
serde = "1.0.214"
serde_json = "1.0.132"
sysinfo = "0.32.0"
